routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Rutas Autenticacion
Auth::routes();

//Ruta Inicio Publico
Route::get('/', 'HomePublicController@index');

//Rutas Tablero
Route::get('/tablero', 'HomeAuthController@index')->name('home')->middleware(['auth', 'usuario_estado']);
Route::get('/tablero_ambientes_programados', 'HomeAuthController@ambientes_programados')->name('ambientes_programados')->middleware('auth');
Route::get('/tablero_usuarios_registrados', 'HomeAuthController@usuarios_registrados')->name('usuarios_registrados')->middleware('auth');

//Rutas Ambientes
Route::resource('/ambientes', 'AmbientesController')->middleware('auth');
Route::get('/gestionar_programa/{id_ambiente}', 'AmbientesController@gestionar_programa')->name('ambientes.gestionar_programa')->middleware('auth');
Route::post('/store_programa/{id_ambiente}', 'AmbientesController@store_programa')->name('ambientes.store_programa')->middleware('auth');
Route::get('/ambientes_programa/{id_programa}', 'AmbientesController@get_ambientes')->name('ambientes_programa.getambientes');
Route::any('/buscar_ambientes', 'AmbientesController@buscar_ambientes')->name('buscar.ambiente')->middleware('auth');
Route::get('/autocompletar_productos','AmbientesController@autocompletar_productos')->name('autocompletar.productos')->middleware('auth');

//Rutas Centros de Formación
Route::resource('/centros_formacion', 'CentrosFormacionController')->middleware('auth');
Route::any('/buscar_centros_formacion', 'CentrosFormacionController@buscar_centros_formacion')->name('buscar.centro_formacion')->middleware('auth');

//Ruta Anidada de Sedes
Route::resource('/centros_formacion.sedes', 'CentrosFormacionSedesController')->middleware('auth');
Route::post('/sedes_ambientes', 'AmbientesController@store_sede')->name('registro.sedes')->middleware('auth');

//Rutas Programas de Formación
Route::resource('/programas_formacion', 'ProgramasFormacionController')->middleware('auth');
Route::resource('/programas_formacion.fichas', 'ProgramasFormacionFichasController')->middleware('auth');
Route::resource('/programas_formacion.actividades', 'ProgramasFormacionActividadesController')->middleware('auth');
Route::any('/buscar_programas_formacion', 'ProgramasFormacionController@buscar_programas_formacion')->name('buscar.programa_formacion')->middleware('auth');

//Rutas Redes de Conocimiento
Route::resource('/redes_conocimiento', 'RedesConocimientoController')->middleware('auth');
Route::get('/redes_conocimiento/lineas_tematicas/{idred}', 'RedesConocimientoController@lineas_red')->name('lineas.red')->middleware('auth');
Route::any('/buscar_redes_conocimiento', 'RedesConocimientoController@buscar_redes_conocimiento')->name('buscar.red_conocimiento')->middleware('auth');

Route::get('/redes/lineas/{idredconocimiento}', 'RedesConocimientoController@get_lineas')->name('redes.getlinea');
Route::get('/redes/programas/{id_linea_tematica}', 'RedesConocimientoController@get_programas')->name('redes.getprograma');

//Ruta Anidada de Lineas Temáticas
Route::resource('/redes_conocimiento.lineas_tematicas', 'RedesConocimientoLineasTematicasController')->middleware('auth');

Route::get('/regionales/municipios/{id_regional}', 'RegionalesController@get_municipios')->name('regionales.getmunicipio');
Route::get('/regionales/centros/{id_municipio}', 'RegionalesController@get_centros')->name('regionales.getcentro');
Route::get('/regionales/sedes/{id_centro_formacion}', 'RegionalesController@get_sedes')->name('regionales.getsede');

//Rutas Usuarios
Route::resource('/usuarios', 'UsuariosController')->middleware('auth');
Route::patch('/usuarios_acceso/{id}{estado}', 'UsuariosController@usuarios_acceso')->name('usuarios.usuarios_acceso')->middleware('auth');
Route::get('/usuario_perfil/{id}', 'UsuariosController@edit_perfil')->name('usuario.perfil')->middleware('auth');
Route::put('/update_perfil/{id}', 'UsuariosController@update_perfil')->name('usuario.update_perfil')->middleware('auth');
Route::any('/buscar_usuarios', 'UsuariosController@buscar_usuarios')->name('buscar.usuario')->middleware('auth');

//Rutas Espacios Complementarios
Route::resource('/espacios_complementarios', 'EspaciosComplementariosController');
Route::get('/gestionar_espacios_complementarios/{id_ambiente}', 'EspaciosComplementariosController@gestionar_espacios_complementarios')->middleware('auth')->name('espacios_complementarios.gestionar_espacios_complementarios');
Route::get('/create_espacios_complementarios/{id_ambiente}', 'EspaciosComplementariosController@create_espacios_complementarios')->middleware('auth')->name('espacios_complementarios.create_espacios_complementarios');
Route::delete('/delete_espacios_complementarios/{id_espacio}/{id_ambiente}', 'EspaciosComplementariosController@delete_espacios_complementarios')->middleware('auth')->name('espacios_complementarios.delete_espacios_complementarios');

//Rutas Programas Formacion de Ambientes
Route::resource('/programas_formacion_ambiente', 'AmbientesProgramaFormacionController');
Route::get('/gestionar_programas_ambiente/{id_ambiente}', 'AmbientesProgramaFormacionController@gestionar_programas_ambiente')->middleware('auth')->name('programas_formacion_ambiente.gestionar_programas_ambiente');
Route::get('/create_programas_ambiente/{id_ambiente}', 'AmbientesProgramaFormacionController@create_programas_ambiente')->middleware('auth')->name('programas_formacion_ambiente.create_programas_ambiente');
Route::delete('/delete_programas_ambiente/{id_programa}/{id_ambiente}', 'AmbientesProgramaFormacionController@delete_programas_ambiente')->middleware('auth')->name('programas_formacion_ambiente.delete_programas_ambiente');

//Rutas Reportes
Route::get('/reportes', 'ReportesController@index')->name('reportes.index')->middleware('auth');
Route::post('/reporte_ambientes', 'ReportesController@store_ambientes')->name('reportes.store_ambientes')->middleware('auth');
Route::post('/reporte_centros_formacion', 'ReportesController@store_centros_formacion')->name('reportes.store_centros_formacion')->middleware('auth');
Route::post('/reporte_redes_conocimiento', 'ReportesController@store_redes_conocimiento')->name('reportes.store_redes_conocimiento')->middleware('auth');
Route::post('/reporte_programas_formacion', 'ReportesController@store_programas_formacion')->name('reportes.store_programas_formacion')->middleware('auth');

//Rutas Gestion Ambientes
Route::resource('/ambientes.elementos', 'AmbienteElementoController')->middleware('auth');
Route::get('/importar_elementos/{id_ambiente}', 'AmbienteElementoController@importar_elementos')->name('importar.elementos')->middleware('auth');
Route::post('/almacenar_elementos/{id_ambiente}', 'AmbienteElementoController@almacenar_elementos')->name('almacenar.elementos')->middleware('auth');
Route::post('/validacion_elemento/{id_ambiente}', 'AmbienteElementoController@validacion_elemento')->name('validacion.elemento')->middleware('auth');

//Rutas Perfiles Administración
Route::resource('/perfiles', 'PerfilesController')->middleware('auth');
Route::get('/gestionar_permisos', 'PerfilesController@gestionar_permisos')->name('perfiles.gestionar_permisos')->middleware('auth');
Route::post('/perfiles_permisos', 'PerfilesController@gestion_permisos')->name('perfiles.gestionpermisos')->middleware('auth');

//Rutas Elementos Administración
Route::resource('/elementos', 'ElementosController')->middleware('auth');
Route::post('/elementos_importacion', 'ElementosController@store_importacion')->name('elementos.store_importacion')->middleware('auth');
Route::get('/elementos_subcategorias/{id_categoria_elemento}', 'ElementosController@get_subcategorias_elementos')->name('elementos_subcategorias.getsubcategorias')->middleware('auth');
Route::get('/elementos_plantilla', 'ElementosController@exportar_plantilla')->name('elementos.exportar_plantilla')->middleware('auth');

//Rutas Programacion Ambientes
Route::resource('/programaciones_ambiente', 'ProgramacionesAmbienteController')->middleware('auth');
Route::get('/programaciones_ambiente_filtro', 'ProgramacionesAmbienteController@filtro_programacion')->name('programaciones_ambiente.filtro')->middleware('auth');
Route::post('/programaciones_ambiente_calendario', 'ProgramacionesAmbienteController@calendario_programacion')->name('programaciones_ambiente.calendario')->middleware('auth');
Route::get('/programaciones_ambiente_eventos', 'ProgramacionesAmbienteController@calendario_eventos')->name('programaciones_ambiente.eventos')->middleware('auth');
Route::get('/programaciones_ambiente_festivos', 'ProgramacionesAmbienteController@calendario_festivos')->name('programaciones_ambiente.festivos')->middleware('auth');
Route::get('/programaciones_ambiente_exportar/{id}/{filtro}', 'ProgramacionesAmbienteController@exportar_programacion')->name('programaciones_ambiente.exportar')->middleware('auth');

Route::get('/programas_ambiente/{id_ambiente}', 'ProgramacionesAmbienteController@programas_ambiente')->name('programas_ambiente.getprogramas')->middleware('auth');
Route::get('/fichas_programa/{id_programa}', 'ProgramacionesAmbienteController@fichas_programa')->name('fichas_programa.getfichas')->middleware('auth');
Route::get('/competencias_programa/{id_programa}', 'ProgramacionesAmbienteController@competencias_programa')->name('competencias_programa.getcompetencias')->middleware('auth');
Route::get('/resultados_programa/{id_competencia}/{id_ficha}', 'ProgramacionesAmbienteController@resultados_programa')->name('resultados_programa.getresultados')->middleware('auth');

resources/views/admin/redes/actualizar.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="row">
    <div class="col-1 d-none d-lg-flex">
        <a href="{{route('redes_conocimiento.index')}}" class="btn btn-lg">
            <i class="fas fa-arrow-alt-circle-left fa-2x" data-toggle="tooltip" title="Regresar" id="icono-v"></i>
        </a>
    </div>
    <div class="col-12 col-sm-10 col-lg-8 offset-sm-1">
        <div class="card card-outline card-sena elevation-2">
            <div class="card-body">
                <div class="col-12 mt-2 mb-4 text-center">
                    <h3 class="card-title">Actualizar Red de Conocimiento</h3>
                </div>
                <form class="needs-validation" method="POST" action="{{route('redes_conocimiento.update',$red->idredconocimiento)}}" novalidate>
                    @csrf
                    @method('PUT')
                    <div class="form-row justify-content-center">
                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="redconocimiento"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Nombre Red de Conocimiento</label>
                            <input type="text" class="form-control" name="redconocimiento" id="redconocimiento" value="{{$red->redconocimiento}}" placeholder="Ej: Mecánica Industrial" maxlength="100" required>
                            <div class="invalid-feedback">
                                Escriba el Nombre de la Red de Conocimiento
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="nombre_gestor"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Nombre Gestor</label>
                            <input type="text" class="form-control" name="nombre_gestor" id="nombre_gestor" value="{{$red->nombre_gestor}}" placeholder="Ej: William Andres Suarez Benavides" maxlength="80" required>
                            <div class="invalid-feedback">
                                Escriba el Nombre del Gestor de la Red de Conocimiento
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="tel_gestor"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Teléfono Gestor</label>
                            <input type="number" class="form-control" name="tel_gestor" id="tel_gestor" value="{{$red->tel_gestor}}" placeholder="Ej: 0324353787" min="1" max="9999999999" required>
                            <div class="invalid-feedback">
                                Escriba el Teléfono del Gestor de la Red de Conocimiento
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="mail_gestor"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Correo Electrónico Gestor</label>
                            <input type="email" class="form-control" name="mail_gestor" id="mail_gestor" value="{{$red->mail_gestor}}" placeholder="Ej: william@gmail.com" maxlength="50" required>
                            <div class="invalid-feedback">
                                Escriba el Correo Electrónico del Gestor de la Red de Conocimiento
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="text"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Nombre Dinamizador</label>
                            <input type="text" class="form-control" name="nombre_asesor" id="nombre_asesor" value="{{$red->nombre_asesor}}" placeholder="Ej: Cristhian David Gomez Muñoz" maxlength="80" required>
                            <div class="invalid-feedback">
                                Escriba el Nombre del Dinamizador de la Red de Conocimiento
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="text"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Teléfono Dinamizador</label>
                            <input type="number" class="form-control" name="tel_asesor" id="tel_asesor" value="{{$red->tel_asesor}}" placeholder="Ej: 0324352238" min="1" max="9999999999" required>
                            <div class="invalid-feedback">
                                Escriba el Teléfono del Dinamizador de la Red de Conocimiento
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="text"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Correo Electrónico Dinamizador</label>
                            <input type="email" class="form-control" name="mail_asesor" id="mail_asesor" value="{{$red->mail_asesor}}" placeholder="Ej: cristhian@gmail.com" maxlength="50" required>
                             <div class="invalid-feedback">
                                Escriba el Correo Electrónico del Dinamizador de la Red de Conocimiento
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8 mt-3 mb-4">
                            <button class="btn w-100 btn-naranja" type="submit">Actualizar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/redes/detalle.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="row">
    <div class="col-1 d-none d-lg-flex">
        <a href="{{route('redes_conocimiento.index')}}" class="btn btn-lg">
            <i class="fas fa-arrow-alt-circle-left fa-2x" data-toggle="tooltip" title="Regresar" id="icono-v"></i>
        </a>
    </div>
    <div class="col-12 col-sm-10 col-lg-8 offset-sm-1">
        <div class="card card-outline card-sena elevation-2">
            <div class="card-body">
                <div class="col-12 mt-2 mb-4 text-center">
                    <h3 class="card-title">Detalles Red de Conocimiento</h3>
                </div>
                <div class="form-row justify-content-center">
                    <div class="form-group col-10 col-lg-8">
                        <label  class="form-label" for="text">Red de Conocimiento</label>
                        @if ($red->redconocimiento != null)
                            <h6>{{$red->redconocimiento}}</h6>
                        @else
                            <h6>Sin registrar</h6>
                        @endif
                    </div>

                    <div class="form-group col-10 col-lg-8">
                        <label class="form-label" for="nombre_gestor">Nombre Gestor</label>
                        @if ($red->nombre_gestor != null)
                            <h6>{{$red->nombre_gestor}}</h6>
                        @else
                            <h6>Sin registrar</h6>
                        @endif
                    </div>

                    <div class="form-group col-10 col-lg-8">
                        <label class="form-label" for="telefono_gestor">Teléfono Gestor</label>
                        @if ($red->tel_gestor != null)
                            <h6>{{$red->tel_gestor}}</h6>
                        @else
                            <h6>Sin registrar</h6>
                        @endif
                    </div>

                    <div class="form-group col-10 col-lg-8">
                        <label class="form-label" for="correo_gestor">Correo Electrónico Gestor</label>
                        @if ($red->mail_gestor != null)
                            <h6>{{$red->mail_gestor}}</h6>
                        @else
                            <h6>Sin registrar</h6>
                        @endif
                    </div>

                    <div class="form-group col-10 col-lg-8">
                        <label class="form-label" for="nombre_asesor">Nombre Dinamizador</label>
                        @if ($red->nombre_asesor != null)
                            <h6>{{$red->nombre_asesor}}</h6>
                        @else
                            <h6>Sin registrar</h6>
                        @endif
                    </div>
                    
                    <div class="form-group col-10 col-lg-8">
                        <label class="form-label" for="telefono_asesor">Teléfono Dinamizador</label>
                        @if ($red->tel_asesor != null)
                            <h6>{{$red->tel_asesor}}</h6>
                        @else
                            <h6>Sin registrar</h6>
                        @endif
                    </div>

                    <div class="form-group col-10 col-lg-8">
                        <label class="form-label" for="correo_asesor">Correo Electrónico Dinamizador</label>
                        @if ($red->mail_asesor != null)
                            <h6>{{$red->mail_asesor}}</h6>
                        @else
                            <h6>Sin registrar</h6>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/redes/gestionar.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="row mb-4">
    <div class="col-12 col-lg-6 offset-lg-3">
        <h3 class="card-title">Gestionar Redes de Conocimiento</h3>
    </div>
    <div class="col-12 col-sm-10 col-lg-3 offset-sm-1 offset-lg-0 mt-4 mt-lg-0">
        <form action="{{route('buscar.red_conocimiento')}}" method="POST">
            @csrf
            <div class="input-group">
                <input type="text" name="buscar_red_conocimiento" class="form-control" placeholder="Buscar Red Conocimiento">
                <div class="input-group-append">
                    <div class="input-group-text pt-0 pb-0">
                        <button class="btn p-0" type="submit">
                            <i class="fas fa-search color-naranja"></i>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@if (count($redes) > 0)
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card card-outline card-sena elevation-2">
                <div class="card-body">
                    <!-- Tabla de registros -->
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class="table-header">
                                <tr>
                                    <th>N°</th>
                                    <th>Red Conocimiento</th>
                                    <th>Gestor</th>
                                    <th>Teléfono</th>
                                    <th>Correo Electrónico</th>
                                    <th class="text-center">Acciones</th>
                                </tr>
                            </thead>
                            <tbody class="table-body">
                                @foreach ($redes as $r)
                                <tr>
                                    <th scope="row">{{$loop->iteration}}</th>
                                    <td class="text-truncate" style="max-width: 250px;">{{$r->redconocimiento}}</td>
                                    <td class="text-truncate" style="max-width: 200px;">{{$r->nombre_gestor}}</td>
                                    <td>{{$r->tel_gestor}}</td>
                                    <td>{{$r->mail_gestor}}</td>
                                    <td class="text-center">
                                        <div class="row justify-content-center">
                                            <div class="col-4 col-lg-3">
                                                <a href="{{route('redes_conocimiento.show',$r->idredconocimiento)}}" type="button">
                                                    <i class="fas fa-eye" data-toggle="tooltip" title="Detalles Red"></i>
                                                </a>
                                            </div>
                                            <div class="col-4 col-lg-3">
                                                <a href="{{route('redes_conocimiento.edit',$r->idredconocimiento)}}" type="button">
                                                    <i class="fas fa-edit" data-toggle="tooltip" title="Actualizar Red"></i>
                                                </a>
                                            </div>
                                            <div class="col-4 col-lg-3">
                                                <a href="{{route('redes_conocimiento.lineas_tematicas.index',$r->idredconocimiento)}}" type="button">
                                                    <i class="fas fa-list" data-toggle="tooltip" title="Gestionar Lineas Tecnológicas"></i>
                                                </a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="float-right mt-2">
                            {{ $redes->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@else
    <h4 class="mt-5" style="text-align: center">No hay redes de conocimiento registradas</h4>
@endif
@endsection

resources/views/admin/redes/registro.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="row justify-content-center">
    <div class="col-12 col-sm-10 col-lg-8">
        <div class="card card-outline card-sena elevation-2">
            <div class="card-body">
                <div class="col-12 mt-2 mb-4 text-center">
                    <h3 class="card-title">Registro Red de Conocimiento</h3>
                </div>
                <form class="needs-validation" method="POST" action="{{route('redes_conocimiento.store')}}" novalidate>
                    @csrf
                    <div class="form-row justify-content-center">
                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="redconocimiento"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Nombre Red de Conocimiento</label>
                            <input type="text" class="form-control" name="redconocimiento" id="redconocimiento" placeholder="Ej: Mecánica Industrial" maxlength="100" autofocus required>
                            <div class="invalid-feedback">
                                Escriba el Nombre de la Red de Conocimiento
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="nombre_gestor"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Nombre Gestor</label>
                            <input type="text" class="form-control" name="nombre_gestor" id="nombre_gestor" placeholder="Ej: William Andres Suarez Benavides" maxlength="80" required>
                            <div class="invalid-feedback">
                                Escriba el Nombre del Gestor de la Red de Conocimiento
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="tel_gestor"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Teléfono Gestor</label>
                            <input type="number" class="form-control" name="tel_gestor" id="tel_gestor" placeholder="Ej: 0324353787" min="1" max="9999999999" required>
                            <div class="invalid-feedback">
                                Escriba el Teléfono del Gestor de la Red de Conocimiento
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="mail_gestor"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Correo Electrónico Gestor</label>
                            <input type="email" class="form-control" name="mail_gestor" id="mail_gestor" placeholder="Ej: william@gmail.com" maxlength="50" required>
                            <div class="invalid-feedback">
                                Escriba el Correo Electrónico del Gestor de la Red de Conocimiento
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="nombre_asesor"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Nombre Dinamizador</label>
                            <input type="text" class="form-control" name="nombre_asesor" id="nombre_asesor" placeholder="Ej: Cristhian David Gomez Muñoz" maxlength="80" required>
                            <div class="invalid-feedback">
                                Escriba el Nombre del Dinamizador de la Red de Conocimiento
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="tel_asesor"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Teléfono Dinamizador</label>
                            <input type="number" class="form-control" name="tel_asesor" id="tel_asesor" placeholder="Ej: 0324352238" min="1" max="9999999999" required>
                            <div class="invalid-feedback">
                                Escriba el Teléfono del Dinamizador de la Red de Conocimiento
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="mail_asesor"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Correo Electrónico Dinamizador</label>
                            <input type="email" class="form-control" name="mail_asesor" id="mail_asesor" placeholder="Ej: cristhian@gmail.com" maxlength="50" required>
                            <div class="invalid-feedback">
                                Escriba el Correo Electrónico del Dinamizador de la Red de Conocimiento
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8 mt-3 mb-4">
                            <button class="btn w-100 btn-naranja" type="submit">Registrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection