routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Rutas Autenticacion
Auth::routes();

//Ruta Inicio Publico
Route::get('/', 'HomePublicController@index');

//Rutas Tablero
Route::get('/tablero', 'HomeAuthController@index')->name('home')->middleware(['auth', 'usuario_estado']);
Route::get('/tablero_ambientes_programados', 'HomeAuthController@ambientes_programados')->name('ambientes_programados')->middleware('auth');
Route::get('/tablero_usuarios_registrados', 'HomeAuthController@usuarios_registrados')->name('usuarios_registrados')->middleware('auth');

//Rutas Ambientes
Route::resource('/ambientes', 'AmbientesController')->middleware('auth');
Route::get('/gestionar_programa/{id_ambiente}', 'AmbientesController@gestionar_programa')->name('ambientes.gestionar_programa')->middleware('auth');
Route::post('/store_programa/{id_ambiente}', 'AmbientesController@store_programa')->name('ambientes.store_programa')->middleware('auth');
Route::get('/ambientes_programa/{id_programa}', 'AmbientesController@get_ambientes')->name('ambientes_programa.getambientes');
Route::any('/buscar_ambientes', 'AmbientesController@buscar_ambientes')->name('buscar.ambiente')->middleware('auth');
Route::get('/autocompletar_productos','AmbientesController@autocompletar_productos')->name('autocompletar.productos')->middleware('auth');

//Rutas Centros de Formación
Route::resource('/centros_formacion', 'CentrosFormacionController')->middleware('auth');
Route::any('/buscar_centros_formacion', 'CentrosFormacionController@buscar_centros_formacion')->name('buscar.centro_formacion')->middleware('auth');

//Ruta Anidada de Sedes
Route::resource('/centros_formacion.sedes', 'CentrosFormacionSedesController')->middleware('auth');
Route::post('/sedes_ambientes', 'AmbientesController@store_sede')->name('registro.sedes')->middleware('auth');

//Rutas Programas de Formación
Route::resource('/programas_formacion', 'ProgramasFormacionController')->middleware('auth');
Route::resource('/programas_formacion.fichas', 'ProgramasFormacionFichasController')->middleware('auth');
Route::resource('/programas_formacion.actividades', 'ProgramasFormacionActividadesController')->middleware('auth');
Route::any('/buscar_programas_formacion', 'ProgramasFormacionController@buscar_programas_formacion')->name('buscar.programa_formacion')->middleware('auth');

//Rutas Redes de Conocimiento
Route::resource('/redes_conocimiento', 'RedesConocimientoController')->middleware('auth');
Route::get('/redes_conocimiento/lineas_tematicas/{idred}', 'RedesConocimientoController@lineas_red')->name('lineas.red')->middleware('auth');
Route::any('/buscar_redes_conocimiento', 'RedesConocimientoController@buscar_redes_conocimiento')->name('buscar.red_conocimiento')->middleware('auth');

Route::get('/redes/lineas/{idredconocimiento}', 'RedesConocimientoController@get_lineas')->name('redes.getlinea');
Route::get('/redes/programas/{id_linea_tematica}', 'RedesConocimientoController@get_programas')->name('redes.getprograma');

//Ruta Anidada de Lineas Temáticas
Route::resource('/redes_conocimiento.lineas_tematicas', 'RedesConocimientoLineasTematicasController')->middleware('auth');

Route::get('/regionales/municipios/{id_regional}', 'RegionalesController@get_municipios')->name('regionales.getmunicipio');
Route::get('/regionales/centros/{id_municipio}', 'RegionalesController@get_centros')->name('regionales.getcentro');
Route::get('/regionales/sedes/{id_centro_formacion}', 'RegionalesController@get_sedes')->name('regionales.getsede');

//Rutas Usuarios
Route::resource('/usuarios', 'UsuariosController')->middleware('auth');
Route::patch('/usuarios_acceso/{id}{estado}', 'UsuariosController@usuarios_acceso')->name('usuarios.usuarios_acceso')->middleware('auth');
Route::get('/usuario_perfil/{id}', 'UsuariosController@edit_perfil')->name('usuario.perfil')->middleware('auth');
Route::put('/update_perfil/{id}', 'UsuariosController@update_perfil')->name('usuario.update_perfil')->middleware('auth');
Route::any('/buscar_usuarios', 'UsuariosController@buscar_usuarios')->name('buscar.usuario')->middleware('auth');

//Rutas Espacios Complementarios
Route::resource('/espacios_complementarios', 'EspaciosComplementariosController');
Route::get('/gestionar_espacios_complementarios/{id_ambiente}', 'EspaciosComplementariosController@gestionar_espacios_complementarios')->middleware('auth')->name('espacios_complementarios.gestionar_espacios_complementarios');
Route::get('/create_espacios_complementarios/{id_ambiente}', 'EspaciosComplementariosController@create_espacios_complementarios')->middleware('auth')->name('espacios_complementarios.create_espacios_complementarios');
Route::delete('/delete_espacios_complementarios/{id_espacio}/{id_ambiente}', 'EspaciosComplementariosController@delete_espacios_complementarios')->middleware('auth')->name('espacios_complementarios.delete_espacios_complementarios');

//Rutas Programas Formacion de Ambientes
Route::resource('/programas_formacion_ambiente', 'AmbientesProgramaFormacionController');
Route::get('/gestionar_programas_ambiente/{id_ambiente}', 'AmbientesProgramaFormacionController@gestionar_programas_ambiente')->middleware('auth')->name('programas_formacion_ambiente.gestionar_programas_ambiente');
Route::get('/create_programas_ambiente/{id_ambiente}', 'AmbientesProgramaFormacionController@create_programas_ambiente')->middleware('auth')->name('programas_formacion_ambiente.create_programas_ambiente');
Route::delete('/delete_programas_ambiente/{id_programa}/{id_ambiente}', 'AmbientesProgramaFormacionController@delete_programas_ambiente')->middleware('auth')->name('programas_formacion_ambiente.delete_programas_ambiente');

//Rutas Reportes
Route::get('/reportes', 'ReportesController@index')->name('reportes.index')->middleware('auth');
Route::post('/reporte_ambientes', 'ReportesController@store_ambientes')->name('reportes.store_ambientes')->middleware('auth');
Route::post('/reporte_centros_formacion', 'ReportesController@store_centros_formacion')->name('reportes.store_centros_formacion')->middleware('auth');
Route::post('/reporte_redes_conocimiento', 'ReportesController@store_redes_conocimiento')->name('reportes.store_redes_conocimiento')->middleware('auth');
Route::post('/reporte_programas_formacion', 'ReportesController@store_programas_formacion')->name('reportes.store_programas_formacion')->middleware('auth');

//Rutas Gestion Ambientes
Route::resource('/ambientes.elementos', 'AmbienteElementoController')->middleware('auth');
Route::get('/importar_elementos/{id_ambiente}', 'AmbienteElementoController@importar_elementos')->name('importar.elementos')->middleware('auth');
Route::post('/almacenar_elementos/{id_ambiente}', 'AmbienteElementoController@almacenar_elementos')->name('almacenar.elementos')->middleware('auth');
Route::post('/validacion_elemento/{id_ambiente}', 'AmbienteElementoController@validacion_elemento')->name('validacion.elemento')->middleware('auth');

//Rutas Perfiles Administración
Route::resource('/perfiles', 'PerfilesController')->middleware('auth');
Route::get('/gestionar_permisos', 'PerfilesController@gestionar_permisos')->name('perfiles.gestionar_permisos')->middleware('auth');
Route::post('/perfiles_permisos', 'PerfilesController@gestion_permisos')->name('perfiles.gestionpermisos')->middleware('auth');

//Rutas Elementos Administración
Route::resource('/elementos', 'ElementosController')->middleware('auth');
Route::post('/elementos_importacion', 'ElementosController@store_importacion')->name('elementos.store_importacion')->middleware('auth');
Route::get('/elementos_subcategorias/{id_categoria_elemento}', 'ElementosController@get_subcategorias_elementos')->name('elementos_subcategorias.getsubcategorias')->middleware('auth');
Route::get('/elementos_plantilla', 'ElementosController@exportar_plantilla')->name('elementos.exportar_plantilla')->middleware('auth');

//Rutas Programacion Ambientes
Route::resource('/programaciones_ambiente', 'ProgramacionesAmbienteController')->middleware('auth');
Route::get('/programaciones_ambiente_filtro', 'ProgramacionesAmbienteController@filtro_programacion')->name('programaciones_ambiente.filtro')->middleware('auth');
Route::post('/programaciones_ambiente_calendario', 'ProgramacionesAmbienteController@calendario_programacion')->name('programaciones_ambiente.calendario')->middleware('auth');
Route::get('/programaciones_ambiente_eventos', 'ProgramacionesAmbienteController@calendario_eventos')->name('programaciones_ambiente.eventos')->middleware('auth');
Route::get('/programaciones_ambiente_festivos', 'ProgramacionesAmbienteController@calendario_festivos')->name('programaciones_ambiente.festivos')->middleware('auth');
Route::get('/programaciones_ambiente_exportar/{id}/{filtro}', 'ProgramacionesAmbienteController@exportar_programacion')->name('programaciones_ambiente.exportar')->middleware('auth');

Route::get('/programas_ambiente/{id_ambiente}', 'ProgramacionesAmbienteController@programas_ambiente')->name('programas_ambiente.getprogramas')->middleware('auth');
Route::get('/fichas_programa/{id_programa}', 'ProgramacionesAmbienteController@fichas_programa')->name('fichas_programa.getfichas')->middleware('auth');
Route::get('/competencias_programa/{id_programa}', 'ProgramacionesAmbienteController@competencias_programa')->name('competencias_programa.getcompetencias')->middleware('auth');
Route::get('/resultados_programa/{id_competencia}/{id_ficha}', 'ProgramacionesAmbienteController@resultados_programa')->name('resultados_programa.getresultados')->middleware('auth');

resources/views/admin/centros/actualizar.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="row">
    <div class="col-1 d-none d-lg-flex">
        <a href="{{route('centros_formacion.index')}}" class="btn btn-lg">
            <i class="fas fa-arrow-alt-circle-left fa-2x" data-toggle="tooltip" title="Regresar" id="icono-v"></i>
        </a>
    </div>
    <div class="col-12 col-sm-10 col-lg-8 offset-sm-1">
        <div class="card card-outline card-sena elevation-2">
            <div class="card-body">
                <div class="col-12 mt-2 mb-4 text-center">
                    <h3 class="card-title">Actualizar Centro de Formación</h3>
                </div>
                <form class="needs-validation" method="POST" action="{{route('centros_formacion.update',$centro->id_centro_formacion)}}" novalidate>
                    @csrf
                    @method('PUT')
                    <div class="form-row justify-content-center">
                        <div class="form-group col-10 col-lg-8">
                            <label for="id_regional" class="form-label"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Regional</label>
                            <select class="form-control select2 select2-hidden-accessible select2-orange" name="id_regional" id="id_regional" required style="width: 100%;" data-select2-id="id_regional" tabindex="-1" aria-hidden="true" data-dropdown-css-class="select2-orange">
                                <option value="{{$centro->id_regional}}">{{$centro->regional->regional}}</option>
                                @foreach($regional as $r)
                                    <option value="{{$r->id_regional}}">{{$r->regional}}</option>
                                @endforeach
                            </select>
                            <div class="invalid-feedback">
                                Seleccione una Regional
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label for="id_municipio" class="form-label"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Municipio</label>
                            <select class="form-control select2 select2-hidden-accessible select2-orange" name="id_municipio" id="id_municipio" required src="{{route('regionales.getmunicipio','#')}}" style="width: 100%;" data-select2-id="id_municipio" tabindex="-1" aria-hidden="true" data-dropdown-css-class="select2-orange">
                                <option value="{{$centro->id_municipio}}">{{$centro->municipios->municipio}}</option>
                            </select>
                            <div class="invalid-feedback">
                                Seleccione un Municipio
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="centro_formacion"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Nombre Centro de Formación</label>
                            <input type="text" class="form-control" name="centro_formacion" id="centro_formacion" value="{{$centro->centro_formacion}}" placeholder="Ej: Centro de Comercio y Servicios" maxlength="100" required>
                            <div class="invalid-feedback">
                                Escriba el Nombre del Centro de Formación
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="direccion_centro"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Dirección</label>
                            <input type="text" class="form-control" name="direccion_centro" id="direccion_centro" value="{{$centro->direccion_centro}}" placeholder="Ej: Cra 27B #1-22" maxlength="40" required>
                            <div class="invalid-feedback">
                                Escriba la Dirección del Centro de Formación
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="telefono_centro"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Teléfono</label>
                            <input type="number" class="form-control" name="telefono_centro" id="telefono_centro" value="{{$centro->telefono_centro}}" placeholder="Ej: 0328721772" min="1" max="9999999999" required>
                            <div class="invalid-feedback">
                                Escriba el Teléfono del Centro de Formación
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="email_centro"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Correo Electrónico</label>
                            <input type="email" class="form-control" name="email_centro" id="email_centro" value="{{$centro->email_centro}}" placeholder="Ej: comercio_servicios@gmail.com" maxlength="50" required>
                            <div class="invalid-feedback">
                                Escriba el Correo Electrónico del Centro de Formación
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="subdirector"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Nombre Subdirector</label>
                            <input type="text" class="form-control" name="subdirector" id="subdirector" value="{{$centro->subdirector}}" placeholder="Ej: William Andres Suarez Benavides" maxlength="80" required>
                            <div class="invalid-feedback">
                                Escriba el Nombre del Subdirector del Centro de Formación
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="contacto_subdirector"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Correo Electrónico Subdirector</label>
                            <input type="email" class="form-control" name="contacto_subdirector" id="contacto_subdirector" value="{{$centro->contacto_subdirector}}" placeholder="Ej: william@gmail.com" maxlength="50" required>
                            <div class="invalid-feedback">
                                Escriba el Correo Electrónico del Subdirector del Centro de Formación
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8 mt-3 mb-4">
                            <button class="btn w-100 btn-naranja" type="submit">Actualizar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="{{asset('js/registro_centro_formacion.js')}}"></script>
@endsection

resources/views/admin/centros/detalle.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="row">
    <div class="col-1 d-none d-lg-flex">
        <a href="{{route('centros_formacion.index')}}" class="btn btn-lg">
            <i class="fas fa-arrow-alt-circle-left fa-2x" data-toggle="tooltip" title="Regresar" id="icono-v"></i>
        </a>
    </div>
    <div class="col-12 col-sm-10 col-lg-8 offset-sm-1">
        <div class="card card-outline card-sena elevation-2">
            <div class="card-body">
                <div class="col-12 mt-2 mb-4 text-center">
                    <h3 class="card-title">Detalles Centro de Formación</h3>
                </div>
                <div class="form-row justify-content-center">
                    <div class="form-group col-10 col-lg-8">
                        <label class="form-label" for="text">Centro de Formación</label>
                        <h6>{{$centro->centro_formacion}}</h6>
                    </div>

                    <div class="form-group col-10 col-lg-8">
                        <label for="id_regional" class="form-label">Regional</label>
                        <h6>{{$centro->regional->regional}}</h6>
                    </div>

                    <div class="form-group col-10 col-lg-8">
                        <label for="id_municipio" class="form-label">Municipio</label>
                        <h6>{{$centro->municipios->municipio}}</h6>
                    </div>
                    
                    <div class="form-group col-10 col-lg-8">
                        <label class="form-label" for="text">Dirección</label>
                        <h6>{{$centro->direccion_centro}}</h6>
                    </div>

                    <div class="form-group col-10 col-lg-8">
                        <label class="form-label" for="text">Teléfono</label>
                        <h6>{{$centro->telefono_centro}}</h6>
                    </div>

                    <div class="form-group col-10 col-lg-8">
                        <label class="form-label" for="text">Correo Electrónico</label>
                        <h6>{{$centro->email_centro}}</h6>
                    </div>

                    <div class="form-group col-10 col-lg-8">
                        <label class="form-label" for="text">Subdirector</label>
                        <h6>{{$centro->subdirector}}</h6>
                    </div>

                    <div class="form-group col-10 col-lg-8">
                        <label class="form-label" for="text">Contacto Subdirector</label>
                        <h6>{{$centro->contacto_subdirector}}</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/centros/gestionar.blade.php
@extends('admin.layouts.app')
@section('content')
@if (Auth::user()->id_perfil_usuario == 1)
    <div class="row mb-4">
        <div class="col-12 col-lg-6 offset-lg-3">
            <h3 class="card-title">Gestionar Centros de Formación</h3>
        </div>
        <div class="col-12 col-sm-10 col-lg-3 offset-sm-1 offset-lg-0 mt-4 mt-lg-0">
            <form action="{{route('buscar.centro_formacion')}}" method="POST">
                @csrf
                <div class="input-group">
                    <input type="text" name="buscar_centro_formacion" class="form-control" placeholder="Buscar Centro Formación">
                    <div class="input-group-append">
                        <div class="input-group-text pt-0 pb-0">
                            <button class="btn p-0" type="submit">
                                <i class="fas fa-search color-naranja"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@else
    <div class="row justify-content-center mb-4">
        <div class="col-12">
            <h3 class="card-title">Gestionar Centros de Formación</h3>
        </div>
    </div>
@endif

@if (count($centros) > 0)
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-sena elevation-2">
                <div class="card-body">
                    <!-- Tabla de registros -->
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class="table-header">
                                <tr>
                                    <th>N°</th>
                                    <th>Centro Formación</th>
                                    <th>Dirección</th>
                                    <th>Teléfono</th>
                                    <th>Subdirector</th>
                                    <th class="text-center">Acciones</th>
                                </tr>
                            </thead>
                            <tbody class="table-body">
                                @foreach ($centros as $centro)
                                <tr>
                                    <th scope="row">{{$loop->iteration}}</th>
                                    <td class="text-truncate" style="max-width: 200px;">{{$centro->centro_formacion}}</td>
                                    <td class="text-truncate" style="max-width: 150px;">{{$centro->direccion_centro}}</td>
                                    <td>{{$centro->telefono_centro}}</td>
                                    <td class="text-truncate" style="max-width: 150px;">{{$centro->subdirector}}</td>
                                    <td class="text-center">
                                        <div class="row justify-content-center">
                                            <div class="col-4 col-lg-3">
                                                <a href="{{route('centros_formacion.show',$centro->id_centro_formacion)}}" type="button">
                                                    <i class="fas fa-eye" data-toggle="tooltip" title="Detalles Centro"></i>
                                                </a>
                                            </div>
                                            <div class="col-4 col-lg-3">
                                                <a href="{{route('centros_formacion.edit',$centro->id_centro_formacion)}}" type="button">
                                                    <i class="fas fa-edit" data-toggle="tooltip" title="Actualizar Centro"></i>
                                                </a>
                                            </div>
                                            <div class="col-4 col-lg-3">
                                                <a href="{{route('centros_formacion.sedes.index',$centro->id_centro_formacion)}}" type="button">
                                                    <i class="fas fa-building" data-toggle="tooltip" title="Gestionar Sedes"></i>
                                                </a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="float-right">
                            {{ $centros->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@else
    <h4 class="mt-5" style="text-align: center">No hay centros de formación registrados</h4>
@endif
@endsection

resources/views/admin/centros/registro.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="row justify-content-center">
    <div class="col-12 col-sm-10 col-lg-8">
        <div class="card card-outline card-sena elevation-2">
            <div class="card-body">
                <div class="col-12 mt-2 mb-4 text-center">
                    <h3 class="card-title">Registro Centro de Formación</h3>
                </div>
                <form class="needs-validation" method="POST" action="{{route('centros_formacion.store')}}" novalidate>
                    @csrf
                    <div class="form-row justify-content-center">
                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="id_regional"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Regional</label>
                            <select class="form-control select2 select2-hidden-accessible select2-orange" name="id_regional" id="id_regional" required autofocus style="width: 100%;" data-select2-id="id_regional" tabindex="-1" aria-hidden="true" data-dropdown-css-class="select2-orange">
                                <option value="" selected disabled>Seleccione Regional</option>
                                @foreach($regional as $r)
                                    <option value="{{$r->id_regional}}">{{$r->regional}}</option>
                                @endforeach
                            </select>
                            <div class="invalid-feedback">
                                Seleccione una Regional
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="id_municipio"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Municipio</label>
                            <select class="form-control select2 select2-hidden-accessible select2-orange" name="id_municipio" id="id_municipio" required src="{{route('regionales.getmunicipio','#')}}" style="width: 100%;" data-select2-id="id_municipio" tabindex="-1" aria-hidden="true" data-dropdown-css-class="select2-orange">
                                <option value="" selected disabled></option>
                            </select>
                            <div class="invalid-feedback">
                                Seleccione un Municipio
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="centro_formacion"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Nombre Centro de Formación</label>
                            <input type="text" class="form-control" name="centro_formacion" id="centro_formacion" placeholder="Ej: Centro de Comercio y Servicios" maxlength="100" required>
                            <div class="invalid-feedback">
                                Escriba el Nombre del Centro de Formación
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="direccion_centro"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Dirección</label>
                            <input type="text" class="form-control" name="direccion_centro" id="direccion_centro" placeholder="Ej: Cra 27B #1-22" maxlength="40" required>
                            <div class="invalid-feedback">
                                Escriba la Dirección del Centro de Formación
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="telefono_centro"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Teléfono</label>
                            <input type="number" class="form-control" name="telefono_centro" id="telefono_centro" placeholder="Ej: 0328721772" min="1" max="9999999999" required>
                            <div class="invalid-feedback">
                                Escriba el Teléfono del Centro de Formación
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="email_centro"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Correo Electrónico</label>
                            <input type="email" class="form-control" name="email_centro" id="email_centro" placeholder="Ej: comercio_servicios@gmail.com" maxlength="50" required>
                            <div class="invalid-feedback">
                                Escriba el Correo Electrónico del Centro de Formación
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="subdirector"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Nombre Subdirector</label>
                            <input type="text" class="form-control" name="subdirector" id="subdirector" placeholder="Ej: William Andres Suarez Benavides" maxlength="80" required>
                            <div class="invalid-feedback">
                                Escriba el Nombre del Subdirector del Centro de Formación
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="contacto_subdirector"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Correo Electrónico Subdirector</label>
                            <input type="email" class="form-control" name="contacto_subdirector" id="contacto_subdirector" placeholder="Ej: william@sena.edu.co" maxlength="50" required>
                            <div class="invalid-feedback">
                                Escriba el Correo Electrónico del Subdirector del Centro de Formación
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8 mt-3 mb-4">
                            <button class="btn w-100 btn-naranja" type="submit">Registrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="{{asset('js/registro_centro_formacion.js')}}"></script>
@endsection