routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Rutas Autenticacion
Auth::routes();

//Ruta Inicio Publico
Route::get('/', 'HomePublicController@index');

//Rutas Tablero
Route::get('/tablero', 'HomeAuthController@index')->name('home')->middleware(['auth', 'usuario_estado']);
Route::get('/tablero_ambientes_programados', 'HomeAuthController@ambientes_programados')->name('ambientes_programados')->middleware('auth');
Route::get('/tablero_usuarios_registrados', 'HomeAuthController@usuarios_registrados')->name('usuarios_registrados')->middleware('auth');

//Rutas Ambientes
Route::resource('/ambientes', 'AmbientesController')->middleware('auth');
Route::get('/gestionar_programa/{id_ambiente}', 'AmbientesController@gestionar_programa')->name('ambientes.gestionar_programa')->middleware('auth');
Route::post('/store_programa/{id_ambiente}', 'AmbientesController@store_programa')->name('ambientes.store_programa')->middleware('auth');
Route::get('/ambientes_programa/{id_programa}', 'AmbientesController@get_ambientes')->name('ambientes_programa.getambientes');
Route::any('/buscar_ambientes', 'AmbientesController@buscar_ambientes')->name('buscar.ambiente')->middleware('auth');
Route::get('/autocompletar_productos','AmbientesController@autocompletar_productos')->name('autocompletar.productos')->middleware('auth');

//Rutas Centros de Formación
Route::resource('/centros_formacion', 'CentrosFormacionController')->middleware('auth');
Route::any('/buscar_centros_formacion', 'CentrosFormacionController@buscar_centros_formacion')->name('buscar.centro_formacion')->middleware('auth');

//Ruta Anidada de Sedes
Route::resource('/centros_formacion.sedes', 'CentrosFormacionSedesController')->middleware('auth');
Route::post('/sedes_ambientes', 'AmbientesController@store_sede')->name('registro.sedes')->middleware('auth');

//Rutas Programas de Formación
Route::resource('/programas_formacion', 'ProgramasFormacionController')->middleware('auth');
Route::resource('/programas_formacion.fichas', 'ProgramasFormacionFichasController')->middleware('auth');
Route::resource('/programas_formacion.actividades', 'ProgramasFormacionActividadesController')->middleware('auth');
Route::any('/buscar_programas_formacion', 'ProgramasFormacionController@buscar_programas_formacion')->name('buscar.programa_formacion')->middleware('auth');

//Rutas Redes de Conocimiento
Route::resource('/redes_conocimiento', 'RedesConocimientoController')->middleware('auth');
Route::get('/redes_conocimiento/lineas_tematicas/{idred}', 'RedesConocimientoController@lineas_red')->name('lineas.red')->middleware('auth');
Route::any('/buscar_redes_conocimiento', 'RedesConocimientoController@buscar_redes_conocimiento')->name('buscar.red_conocimiento')->middleware('auth');

Route::get('/redes/lineas/{idredconocimiento}', 'RedesConocimientoController@get_lineas')->name('redes.getlinea');
Route::get('/redes/programas/{id_linea_tematica}', 'RedesConocimientoController@get_programas')->name('redes.getprograma');

//Ruta Anidada de Lineas Temáticas
Route::resource('/redes_conocimiento.lineas_tematicas', 'RedesConocimientoLineasTematicasController')->middleware('auth');

Route::get('/regionales/municipios/{id_regional}', 'RegionalesController@get_municipios')->name('regionales.getmunicipio');
Route::get('/regionales/centros/{id_municipio}', 'RegionalesController@get_centros')->name('regionales.getcentro');
Route::get('/regionales/sedes/{id_centro_formacion}', 'RegionalesController@get_sedes')->name('regionales.getsede');

//Rutas Usuarios
Route::resource('/usuarios', 'UsuariosController')->middleware('auth');
Route::patch('/usuarios_acceso/{id}{estado}', 'UsuariosController@usuarios_acceso')->name('usuarios.usuarios_acceso')->middleware('auth');
Route::get('/usuario_perfil/{id}', 'UsuariosController@edit_perfil')->name('usuario.perfil')->middleware('auth');
Route::put('/update_perfil/{id}', 'UsuariosController@update_perfil')->name('usuario.update_perfil')->middleware('auth');
Route::any('/buscar_usuarios', 'UsuariosController@buscar_usuarios')->name('buscar.usuario')->middleware('auth');

//Rutas Espacios Complementarios
Route::resource('/espacios_complementarios', 'EspaciosComplementariosController');
Route::get('/gestionar_espacios_complementarios/{id_ambiente}', 'EspaciosComplementariosController@gestionar_espacios_complementarios')->middleware('auth')->name('espacios_complementarios.gestionar_espacios_complementarios');
Route::get('/create_espacios_complementarios/{id_ambiente}', 'EspaciosComplementariosController@create_espacios_complementarios')->middleware('auth')->name('espacios_complementarios.create_espacios_complementarios');
Route::delete('/delete_espacios_complementarios/{id_espacio}/{id_ambiente}', 'EspaciosComplementariosController@delete_espacios_complementarios')->middleware('auth')->name('espacios_complementarios.delete_espacios_complementarios');

//Rutas Programas Formacion de Ambientes
Route::resource('/programas_formacion_ambiente', 'AmbientesProgramaFormacionController');
Route::get('/gestionar_programas_ambiente/{id_ambiente}', 'AmbientesProgramaFormacionController@gestionar_programas_ambiente')->middleware('auth')->name('programas_formacion_ambiente.gestionar_programas_ambiente');
Route::get('/create_programas_ambiente/{id_ambiente}', 'AmbientesProgramaFormacionController@create_programas_ambiente')->middleware('auth')->name('programas_formacion_ambiente.create_programas_ambiente');
Route::delete('/delete_programas_ambiente/{id_programa}/{id_ambiente}', 'AmbientesProgramaFormacionController@delete_programas_ambiente')->middleware('auth')->name('programas_formacion_ambiente.delete_programas_ambiente');

//Rutas Reportes
Route::get('/reportes', 'ReportesController@index')->name('reportes.index')->middleware('auth');
Route::post('/reporte_ambientes', 'ReportesController@store_ambientes')->name('reportes.store_ambientes')->middleware('auth');
Route::post('/reporte_centros_formacion', 'ReportesController@store_centros_formacion')->name('reportes.store_centros_formacion')->middleware('auth');
Route::post('/reporte_redes_conocimiento', 'ReportesController@store_redes_conocimiento')->name('reportes.store_redes_conocimiento')->middleware('auth');
Route::post('/reporte_programas_formacion', 'ReportesController@store_programas_formacion')->name('reportes.store_programas_formacion')->middleware('auth');

//Rutas Gestion Ambientes
Route::resource('/ambientes.elementos', 'AmbienteElementoController')->middleware('auth');
Route::get('/importar_elementos/{id_ambiente}', 'AmbienteElementoController@importar_elementos')->name('importar.elementos')->middleware('auth');
Route::post('/almacenar_elementos/{id_ambiente}', 'AmbienteElementoController@almacenar_elementos')->name('almacenar.elementos')->middleware('auth');
Route::post('/validacion_elemento/{id_ambiente}', 'AmbienteElementoController@validacion_elemento')->name('validacion.elemento')->middleware('auth');

//Rutas Perfiles Administración
Route::resource('/perfiles', 'PerfilesController')->middleware('auth');
Route::get('/gestionar_permisos', 'PerfilesController@gestionar_permisos')->name('perfiles.gestionar_permisos')->middleware('auth');
Route::post('/perfiles_permisos', 'PerfilesController@gestion_permisos')->name('perfiles.gestionpermisos')->middleware('auth');

//Rutas Elementos Administración
Route::resource('/elementos', 'ElementosController')->middleware('auth');
Route::post('/elementos_importacion', 'ElementosController@store_importacion')->name('elementos.store_importacion')->middleware('auth');
Route::get('/elementos_subcategorias/{id_categoria_elemento}', 'ElementosController@get_subcategorias_elementos')->name('elementos_subcategorias.getsubcategorias')->middleware('auth');
Route::get('/elementos_plantilla', 'ElementosController@exportar_plantilla')->name('elementos.exportar_plantilla')->middleware('auth');

//Rutas Programacion Ambientes
Route::resource('/programaciones_ambiente', 'ProgramacionesAmbienteController')->middleware('auth');
Route::get('/programaciones_ambiente_filtro', 'ProgramacionesAmbienteController@filtro_programacion')->name('programaciones_ambiente.filtro')->middleware('auth');
Route::post('/programaciones_ambiente_calendario', 'ProgramacionesAmbienteController@calendario_programacion')->name('programaciones_ambiente.calendario')->middleware('auth');
Route::get('/programaciones_ambiente_eventos', 'ProgramacionesAmbienteController@calendario_eventos')->name('programaciones_ambiente.eventos')->middleware('auth');
Route::get('/programaciones_ambiente_festivos', 'ProgramacionesAmbienteController@calendario_festivos')->name('programaciones_ambiente.festivos')->middleware('auth');
Route::get('/programaciones_ambiente_exportar/{id}/{filtro}', 'ProgramacionesAmbienteController@exportar_programacion')->name('programaciones_ambiente.exportar')->middleware('auth');

Route::get('/programas_ambiente/{id_ambiente}', 'ProgramacionesAmbienteController@programas_ambiente')->name('programas_ambiente.getprogramas')->middleware('auth');
Route::get('/fichas_programa/{id_programa}', 'ProgramacionesAmbienteController@fichas_programa')->name('fichas_programa.getfichas')->middleware('auth');
Route::get('/competencias_programa/{id_programa}', 'ProgramacionesAmbienteController@competencias_programa')->name('competencias_programa.getcompetencias')->middleware('auth');
Route::get('/resultados_programa/{id_competencia}/{id_ficha}', 'ProgramacionesAmbienteController@resultados_programa')->name('resultados_programa.getresultados')->middleware('auth');

resources/views/admin/actividades/detalle.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="row">
    <div class="col-1 d-none d-lg-flex">
        <a href="{{route('programas_formacion.actividades.index',$id_programa)}}" class="btn btn-lg">
            <i class="fas fa-arrow-alt-circle-left fa-2x" data-toggle="tooltip" title="Regresar" id="icono-v"></i>
        </a>
    </div>
    <div class="col-12 col-sm-10 col-lg-8 offset-sm-1">
        <div class="card card-outline card-sena elevation-2">
            <div class="card-body">
                <div class="col-12 mt-2 mb-4 text-center">
                    <h3 class="card-title">Detalles Actividad de Aprendizaje</h3>
                </div>

                <div class="form-row justify-content-center">
                    <div class="form-group col-10 col-lg-8">
                        <label for="nombre" class="form-label">Actividad Aprendizaje</label>
                        <h6>{{$actividad_aprendizaje->actividad_aprendizaje}}</h6>
                    </div>
                </div>

                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">

                    <ol class="carousel-indicators">
                        @for ($i = 0; $i < count($resultados_aprendizaje); $i++)
                            <li data-target="#carouselExampleControls" data-slide-to="{{$i}}" class="{{$i ? 'active' : ''}}" style="background-color: #FC7323"></li>
                        @endfor
                    </ol>
                    <div class="carousel-inner">
                        @for ($i = 0; $i < count($resultados_aprendizaje); $i++)
                            <div class="carousel-item {{$i ? 'active' : ''}}">
                                <div class="form-row justify-content-center">
                                    <div class="form-group col-10 col-lg-8">
                                        <label for="codigo_competencia" class="form-label">Código Competencia</label>
                                        <h6>{{$resultados_aprendizaje[$i][0]->competencia_laboral->codigo_competencia_laboral}}</h6>
                                    </div>

                                    <div class="form-group col-10 col-lg-8">
                                        <label for="version_competencia" class="form-label">Versión Competencia</label>
                                        <h6>{{$resultados_aprendizaje[$i][0]->competencia_laboral->version_competencia_laboral}}</h6>
                                    </div>

                                    <div class="form-group col-10 col-lg-8">
                                        <label for="competencia" class="form-label">Competencia</label>
                                        <h6>{{$resultados_aprendizaje[$i][0]->competencia_laboral->competencia_laboral}}</h6>
                                    </div>

                                    @for ($j = 0; $j < count($resultados_aprendizaje[$i]); $j++)
                                        <div class="form-group col-10 col-lg-8">
                                            <label for="resultado_aprendizaje" class="form-label">Resultado Aprendizaje</label>
                                            <h6>{{$resultados_aprendizaje[$i][$j]->resultado_aprendizaje}}</h6>
                                        </div>
                                        <div class="form-group col-10 col-lg-8">
                                            <label for="fecha_resultado_aprendizaje" class="form-label">Fecha Terminación</label>
                                            <h6>{{$resultados_aprendizaje[$i][$j]->fecha_terminacion}}</h6>
                                        </div>
                                    @endfor
                                </div>
                            </div>
                        @endfor

                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                            <span><i class="fas fa-chevron-circle-left fa-3x" aria-hidden="true"></i></span>
                            <span class="sr-only">Anterior</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                            <span><i class="fas fa-chevron-circle-right fa-3x" aria-hidden="true"></i></span>
                            <span class="sr-only">Siguiente</span>
                        </a>
                    </div>
                </div>
                           
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/actividades/gestionar.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="row align-items-center mb-3">
    <div class="col-1 d-none d-lg-flex text-left">
        <a href="{{route('programas_formacion.index')}}" class="btn btn-lg">
            <i class="fas fa-arrow-alt-circle-left fa-2x" data-toggle="tooltip" title="Regresar" id="icono-v"></i>
        </a>
    </div>
    <div class="col-8 offset-2 offset-lg-1">
        <h3 class="card-title">Gestionar Actividades de Aprendizaje</h3>
    </div>
    <div class="col-1 offset-1">
        <a href="{{route('programas_formacion.actividades.create', $id_programa)}}" class="btn btn-lg float-right">
            <i class="fas fa-plus-circle fa-2x" data-toggle="tooltip" id="icono-v" title="Registrar Actividad de Aprendizaje"></i>
        </a>
    </div>
</div>
@if (count($actividades_aprendizaje) >= 1)
    <div class="row justify-content-center">
        <div class="col-12 col-sm-10 col-lg-12">
            <div class="card card-outline card-sena elevation-2">
                <div class="card-body">
                    <!-- Tabla de registros -->
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class="table-header">
                                <tr>
                                    <th class="align-top align-lg-middle">N°</th>
                                    <th class="align-top align-lg-middle">Actividad de Aprendizaje</th>
                                    <th class="align-top align-lg-middle text-center">Acciones</th>
                                </tr>
                            </thead>
                            <tbody class="table-body">
                                @foreach ($actividades_aprendizaje as $actividad)
                                    <tr>
                                        <th scope="row">{{$loop->iteration}}</th>
                                        <td>{{$actividad->actividad_aprendizaje}}</td>
                                        <td class="text-center align-top align-lg-middle">
                                            <div class="row justify-content-center">
                                                <div class="col-5 col-lg-5">
                                                    <a href="{{ route('programas_formacion.actividades.show', [$id_programa, $actividad->id_actividad_aprendizaje]) }}">
                                                        <i class="fas fa-eye" data-toggle="tooltip" title="Detalles Actividad"></i>
                                                    </a>
                                                </div>
                                                <div class="col-5 col-lg-5">
                                                    <a href="#" type="button">
                                                        <i class="fas fa-edit" data-toggle="tooltip" title="Actualizar Actividad"></i>
                                                    </a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="float-right">
                            {{ $actividades_aprendizaje ->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@else
    <h4 class="mt-5" style="text-align: center">El programa no tiene actividades de aprendizaje registradas</h4>
@endif
@endsection

resources/views/admin/actividades/registro.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="row">
    <div class="col-1 d-none d-lg-flex">
        <a class="btn btn-lg" href="{{route('programas_formacion.actividades.index',$id_programa)}}">
            <i class="fas fa-arrow-alt-circle-left fa-2x" data-toggle="tooltip" id="icono-v" title="Regresar"></i>
        </a>
    </div>
    <div class="col-12 col-sm-10 col-lg-8 offset-sm-1">
        <div class="card card-outline card-sena elevation-2">
            <div class="card-body">
                <div class="col-12 mt-2 mb-4 text-center">
                    <h3 class="card-title">Registro Actividad de Aprendizaje</h3>
                </div>
                <form class="needs-validation" method="POST" action="{{route('programas_formacion.actividades.store',$id_programa)}}" novalidate>
                    @csrf
                    <div class="form-row justify-content-center">
                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="actividad_aprendizaje"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Actividad Aprendizaje</label>
                            <textarea class="form-control" name="actividad_aprendizaje" id="actividad_aprendizaje" rows="2"
                            placeholder="Ej: Realizar el levantamiento de los requerimientos funcionales y no funcionales para el desarrollo del proyecto"
                            maxlength="200" autofocus required></textarea>
                            <div class="invalid-feedback">
                                Escriba el nombre de la Actividad de Aprendizaje
                            </div>
                        </div>
                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="codigo_competencia_laboral"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Código Competencia</label>
                            <input type="number" class="form-control" name="codigo_competencia_laboral" id="codigo_competencia_laboral" placeholder="Ej: 1008025" min="0" max="99999999" required>
                            <div class="invalid-feedback">
                                Escriba el Código de la Competencia
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="version_competencia_laboral"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Versión Competencia</label>
                            <input type="number" step="any" class="form-control" name="version_competencia_laboral" id="version_competencia_laboral" placeholder="Ej: 102" min="0" max="999" required>
                            <div class="invalid-feedback">
                                Escriba la Versión de la Competencia
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="competencia_laboral"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Competencia</label>
                            <textarea class="form-control" name="competencia_laboral" id="competencia_laboral" rows="4"
                            placeholder="Ej: PARTICIPAR EN EL PROCESO DE NEGOCIACIÓN DE TECNOLOGÍA INFORMÁTICA PARA PERMITIR LA IMPLEMENTACIÓN DEL SISTEMA DE INFORMACIÓN"
                            maxlength="200" required></textarea>
                            <div class="invalid-feedback">
                                Escriba el nombre de la Competencia
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="resultado_aprendizaje"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Resultado Aprendizaje</label>
                            <a class="float-right" href="#">
                                <i class="fas fa-plus-circle fa-2x icon_resultado_aprendizaje" data-toggle="tooltip" id="icono-v" title="Registrar más resultados"></i>
                            </a>
                            <textarea class="form-control" name="resultado_aprendizaje" id="resultado_aprendizaje" rows="6"
                            placeholder="Ej: ELABORAR EL INFORME SOBRE EL CUMPLIMIENTO DE LOS TÉRMINOS DE REFERENCIA PREVISTOS EN LA NEGOCIACIÓN, DE ACUERDO CON LA PARTICIPACIÓN DE CADA UNO DE LOS ACTORES EN RELACIÓN CON LA SATISFACCIÓN DE LOS BIENES INFORMÁTICOS CONTRATADOS Y RECIBIDOS, SEGÚN NORMAS Y PROTOCOLOS DE LA ORGANIZACIÓN"
                            maxlength="200" required></textarea>
                            <div class="invalid-feedback">
                                Escriba el Resultado de Aprendizaje
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="fecha_terminacion"><span class="obligatorio" data-toggle="tooltip" title="Campo Obligatorio">*</span> Fecha Terminación de Resultado Aprendizaje</label>
                            <input type="date" class="form-control" name="fecha_terminacion" id="fecha_terminacion" required>
                            <div class="invalid-feedback">
                                Seleccione la Fecha de Terminación del Resultado de Aprendizaje
                            </div>
                        </div>

                        <div class="form-group col-10 col-lg-8 resultado_aprendizaje">
                        </div>

                        <div class="form-group col-10 col-lg-8 fecha_resultado_aprendizaje">
                        </div>

                        <div class="form-group col-10 col-lg-8 mt-3">
                            <button class="btn btn-naranja w-100" type="submit">Registrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $(".icon_resultado_aprendizaje").on("click", function () {
        var label_resultado_aprendizaje = $("<label></label>").attr({
            class: "form-label"
        }).text("Resultado Aprendizaje");
        var resultado_aprendizaje = $("<textarea></textarea>").attr({
            class: "form-control", name: "resultado_aprendizaje", id: "resultado_aprendizaje", rows: "4",
            placeholder: "Ej: ELABORAR EL INFORME SOBRE EL CUMPLIMIENTO DE LOS TÉRMINOS DE REFERENCIA PREVISTOS EN LA NEGOCIACIÓN, DE ACUERDO CON LA PARTICIPACIÓN DE CADA UNO DE LOS ACTORES EN RELACIÓN CON LA SATISFACCIÓN DE LOS BIENES INFORMÁTICOS CONTRATADOS Y RECIBIDOS, SEGÚN NORMAS Y PROTOCOLOS DE LA ORGANIZACIÓN"
        });

        var icono_eliminar = $("<a></a>").attr({
            class: "float-right", href: "#"
        }).html("<i class='fas fa-minus-circle fa-2x icon_resultado_aprendizaje' id='icono-v'></i>");

        $(".resultado_aprendizaje").append(label_resultado_aprendizaje, icono_eliminar, resultado_aprendizaje);

        var label_fecha_resultado_aprendizaje = $("<label></label>").attr({
            class: "form-label"
        }).text("Fecha Terminación de Resultado Aprendizaje");
        var fecha_resultado_aprendizaje = $("<input/>").attr({
            type: "date", class: "form-control", name: "fecha_resultado_aprendizaje",
            id: "fecha_resultado_aprendizaje"
        });
        $(".fecha_resultado_aprendizaje").append(label_fecha_resultado_aprendizaje, fecha_resultado_aprendizaje);

    });

</script>
@endsection