routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Rutas Autenticacion
Auth::routes();

//Ruta Inicio Publico
Route::get('/', 'HomePublicController@index');

//Rutas Tablero
Route::get('/tablero', 'HomeAuthController@index')->name('home')->middleware(['auth', 'usuario_estado']);
Route::get('/tablero_ambientes_programados', 'HomeAuthController@ambientes_programados')->name('ambientes_programados')->middleware('auth');
Route::get('/tablero_usuarios_registrados', 'HomeAuthController@usuarios_registrados')->name('usuarios_registrados')->middleware('auth');

//Rutas Ambientes
Route::resource('/ambientes', 'AmbientesController')->middleware('auth');
Route::get('/gestionar_programa/{id_ambiente}', 'AmbientesController@gestionar_programa')->name('ambientes.gestionar_programa')->middleware('auth');
Route::post('/store_programa/{id_ambiente}', 'AmbientesController@store_programa')->name('ambientes.store_programa')->middleware('auth');
Route::get('/ambientes_programa/{id_programa}', 'AmbientesController@get_ambientes')->name('ambientes_programa.getambientes');
Route::any('/buscar_ambientes', 'AmbientesController@buscar_ambientes')->name('buscar.ambiente')->middleware('auth');
Route::get('/autocompletar_productos','AmbientesController@autocompletar_productos')->name('autocompletar.productos')->middleware('auth');

//Rutas Centros de Formación
Route::resource('/centros_formacion', 'CentrosFormacionController')->middleware('auth');
Route::any('/buscar_centros_formacion', 'CentrosFormacionController@buscar_centros_formacion')->name('buscar.centro_formacion')->middleware('auth');

//Ruta Anidada de Sedes
Route::resource('/centros_formacion.sedes', 'CentrosFormacionSedesController')->middleware('auth');
Route::post('/sedes_ambientes', 'AmbientesController@store_sede')->name('registro.sedes')->middleware('auth');

//Rutas Programas de Formación
Route::resource('/programas_formacion', 'ProgramasFormacionController')->middleware('auth');
Route::resource('/programas_formacion.fichas', 'ProgramasFormacionFichasController')->middleware('auth');
Route::resource('/programas_formacion.actividades', 'ProgramasFormacionActividadesController')->middleware('auth');
Route::any('/buscar_programas_formacion', 'ProgramasFormacionController@buscar_programas_formacion')->name('buscar.programa_formacion')->middleware('auth');

//Rutas Redes de Conocimiento
Route::resource('/redes_conocimiento', 'RedesConocimientoController')->middleware('auth');
Route::get('/redes_conocimiento/lineas_tematicas/{idred}', 'RedesConocimientoController@lineas_red')->name('lineas.red')->middleware('auth');
Route::any('/buscar_redes_conocimiento', 'RedesConocimientoController@buscar_redes_conocimiento')->name('buscar.red_conocimiento')->middleware('auth');

Route::get('/redes/lineas/{idredconocimiento}', 'RedesConocimientoController@get_lineas')->name('redes.getlinea');
Route::get('/redes/programas/{id_linea_tematica}', 'RedesConocimientoController@get_programas')->name('redes.getprograma');

//Ruta Anidada de Lineas Temáticas
Route::resource('/redes_conocimiento.lineas_tematicas', 'RedesConocimientoLineasTematicasController')->middleware('auth');

Route::get('/regionales/municipios/{id_regional}', 'RegionalesController@get_municipios')->name('regionales.getmunicipio');
Route::get('/regionales/centros/{id_municipio}', 'RegionalesController@get_centros')->name('regionales.getcentro');
Route::get('/regionales/sedes/{id_centro_formacion}', 'RegionalesController@get_sedes')->name('regionales.getsede');

//Rutas Usuarios
Route::resource('/usuarios', 'UsuariosController')->middleware('auth');
Route::patch('/usuarios_acceso/{id}{estado}', 'UsuariosController@usuarios_acceso')->name('usuarios.usuarios_acceso')->middleware('auth');
Route::get('/usuario_perfil/{id}', 'UsuariosController@edit_perfil')->name('usuario.perfil')->middleware('auth');
Route::put('/update_perfil/{id}', 'UsuariosController@update_perfil')->name('usuario.update_perfil')->middleware('auth');
Route::any('/buscar_usuarios', 'UsuariosController@buscar_usuarios')->name('buscar.usuario')->middleware('auth');

//Rutas Espacios Complementarios
Route::resource('/espacios_complementarios', 'EspaciosComplementariosController');
Route::get('/gestionar_espacios_complementarios/{id_ambiente}', 'EspaciosComplementariosController@gestionar_espacios_complementarios')->middleware('auth')->name('espacios_complementarios.gestionar_espacios_complementarios');
Route::get('/create_espacios_complementarios/{id_ambiente}', 'EspaciosComplementariosController@create_espacios_complementarios')->middleware('auth')->name('espacios_complementarios.create_espacios_complementarios');
Route::delete('/delete_espacios_complementarios/{id_espacio}/{id_ambiente}', 'EspaciosComplementariosController@delete_espacios_complementarios')->middleware('auth')->name('espacios_complementarios.delete_espacios_complementarios');

//Rutas Programas Formacion de Ambientes
Route::resource('/programas_formacion_ambiente', 'AmbientesProgramaFormacionController');
Route::get('/gestionar_programas_ambiente/{id_ambiente}', 'AmbientesProgramaFormacionController@gestionar_programas_ambiente')->middleware('auth')->name('programas_formacion_ambiente.gestionar_programas_ambiente');
Route::get('/create_programas_ambiente/{id_ambiente}', 'AmbientesProgramaFormacionController@create_programas_ambiente')->middleware('auth')->name('programas_formacion_ambiente.create_programas_ambiente');
Route::delete('/delete_programas_ambiente/{id_programa}/{id_ambiente}', 'AmbientesProgramaFormacionController@delete_programas_ambiente')->middleware('auth')->name('programas_formacion_ambiente.delete_programas_ambiente');

//Rutas Reportes
Route::get('/reportes', 'ReportesController@index')->name('reportes.index')->middleware('auth');
Route::post('/reporte_ambientes', 'ReportesController@store_ambientes')->name('reportes.store_ambientes')->middleware('auth');
Route::post('/reporte_centros_formacion', 'ReportesController@store_centros_formacion')->name('reportes.store_centros_formacion')->middleware('auth');
Route::post('/reporte_redes_conocimiento', 'ReportesController@store_redes_conocimiento')->name('reportes.store_redes_conocimiento')->middleware('auth');
Route::post('/reporte_programas_formacion', 'ReportesController@store_programas_formacion')->name('reportes.store_programas_formacion')->middleware('auth');

//Rutas Gestion Ambientes
Route::resource('/ambientes.elementos', 'AmbienteElementoController')->middleware('auth');
Route::get('/importar_elementos/{id_ambiente}', 'AmbienteElementoController@importar_elementos')->name('importar.elementos')->middleware('auth');
Route::post('/almacenar_elementos/{id_ambiente}', 'AmbienteElementoController@almacenar_elementos')->name('almacenar.elementos')->middleware('auth');
Route::post('/validacion_elemento/{id_ambiente}', 'AmbienteElementoController@validacion_elemento')->name('validacion.elemento')->middleware('auth');

//Rutas Perfiles Administración
Route::resource('/perfiles', 'PerfilesController')->middleware('auth');
Route::get('/gestionar_permisos', 'PerfilesController@gestionar_permisos')->name('perfiles.gestionar_permisos')->middleware('auth');
Route::post('/perfiles_permisos', 'PerfilesController@gestion_permisos')->name('perfiles.gestionpermisos')->middleware('auth');

//Rutas Elementos Administración
Route::resource('/elementos', 'ElementosController')->middleware('auth');
Route::post('/elementos_importacion', 'ElementosController@store_importacion')->name('elementos.store_importacion')->middleware('auth');
Route::get('/elementos_subcategorias/{id_categoria_elemento}', 'ElementosController@get_subcategorias_elementos')->name('elementos_subcategorias.getsubcategorias')->middleware('auth');
Route::get('/elementos_plantilla', 'ElementosController@exportar_plantilla')->name('elementos.exportar_plantilla')->middleware('auth');

//Rutas Programacion Ambientes
Route::resource('/programaciones_ambiente', 'ProgramacionesAmbienteController')->middleware('auth');
Route::get('/programaciones_ambiente_filtro', 'ProgramacionesAmbienteController@filtro_programacion')->name('programaciones_ambiente.filtro')->middleware('auth');
Route::post('/programaciones_ambiente_calendario', 'ProgramacionesAmbienteController@calendario_programacion')->name('programaciones_ambiente.calendario')->middleware('auth');
Route::get('/programaciones_ambiente_eventos', 'ProgramacionesAmbienteController@calendario_eventos')->name('programaciones_ambiente.eventos')->middleware('auth');
Route::get('/programaciones_ambiente_festivos', 'ProgramacionesAmbienteController@calendario_festivos')->name('programaciones_ambiente.festivos')->middleware('auth');
Route::get('/programaciones_ambiente_exportar/{id}/{filtro}', 'ProgramacionesAmbienteController@exportar_programacion')->name('programaciones_ambiente.exportar')->middleware('auth');

Route::get('/programas_ambiente/{id_ambiente}', 'ProgramacionesAmbienteController@programas_ambiente')->name('programas_ambiente.getprogramas')->middleware('auth');
Route::get('/fichas_programa/{id_programa}', 'ProgramacionesAmbienteController@fichas_programa')->name('fichas_programa.getfichas')->middleware('auth');
Route::get('/competencias_programa/{id_programa}', 'ProgramacionesAmbienteController@competencias_programa')->name('competencias_programa.getcompetencias')->middleware('auth');
Route::get('/resultados_programa/{id_competencia}/{id_ficha}', 'ProgramacionesAmbienteController@resultados_programa')->name('resultados_programa.getresultados')->middleware('auth');

app/Http/Controllers/ElementosController.php
<?php

namespace App\Http\Controllers;

use App\CategoriaElemento;
use App\CentroFormacion;
use App\Exports\PlantillaInventarioExport;
use App\Imports\ElementosImport;
use App\Inventario;
use App\OrigenElemento;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Maatwebsite\Excel\Facades\Excel;
use RealRashid\SweetAlert\Facades\Alert;

class ElementosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.administracion.elementos.importar');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->id_perfil_usuario == 1) {
            $centros_formacion = CentroFormacion::orderBy('centro_formacion', 'asc')->get();
        }
        else {
            $centros_formacion = CentroFormacion::where('id_centro_formacion', '=', Auth::user()->id_centro_formacion)
            ->orderBy('centro_formacion', 'asc')->get();
        }

        $categorias = CategoriaElemento::orderBy('categoria_elemento', 'asc')->get();
        $origenes   = OrigenElemento::orderBy('origen_elemento', 'asc')->get();

        return view('admin.administracion.elementos.registro', compact('centros_formacion', 'categorias', 'origenes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $elementos_inventario_registrados = Inventario::where('numero_inventario', '=', $request->input('numero_inventario'))
        ->orWhere('serial', '=', $request->input('serial'))
        ->first();
       
        if ($elementos_inventario_registrados == null) {
            $inventario = new Inventario;
            $inventario->centro_formacion_id         = $request->input('centro_formacion_id');
            $inventario->subcategoria_elemento_id    = $request->input('subcategoria_elemento_id');
            $inventario->origen_elemento_id          = $request->input('origen_elemento_id');
            $inventario->numero_inventario           = $request->input('numero_inventario');
            $inventario->serial                      = $request->input('serial');
            $inventario->cantidad                    = $request->input('cantidad');
            $inventario->elemento_ambiente           = ucwords(strtolower($request->input('elemento_ambiente')));
            $inventario->estado                      = $request->input('estado');
            $inventario->fecha_adquisicion           = $request->input('fecha_adquisicion');
            $inventario->tiempo_vida_util            = $request->input('tiempo_vida_util');
            $inventario->precio                      = $request->input('precio');
            $inventario->observacion_general         = $request->input('observacion_general');
            $inventario->save();

            Alert::success('Registrado', 'Elemento con éxito, Ya lo puede Asociar al Ambiente');
        }
        else {
            Alert::error('Error', 'El Número de Inventario o Serial ya estan Registrados');
        }
        
        return redirect(route('elementos.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Subcategorias Elementos
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function get_subcategorias_elementos($id_categoria_elemento)
    {
        $subcategorias_elementos = DB::table('subcategoria_elemento')
        ->select('id_subcategoria_elemento', 'subcategoria_elemento')
        ->where('categoria_elemento_id',$id_categoria_elemento)
        ->get();

        foreach ($subcategorias_elementos as $subce) {
            echo "<option value='{$subce->id_subcategoria_elemento}'>{$subce->subcategoria_elemento}</option>";
        }
    }

    /**
     * Importación elementos de administración.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store_importacion(Request $request)
    {
        Excel::import(new ElementosImport, request()->file('elementos'));

        Alert::success('Importados', 'Elementos con éxito');
        return redirect(route('elementos.index'));
    }

     /**
     * Exportación plantilla inventarios.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function exportar_plantilla()
    {
        $exportacion_plantilla = new PlantillaInventarioExport();
        return Excel::download($exportacion_plantilla, 'Plantilla_Inventarios.xlsx');

    }
}

resources/views/admin/ambientes/elementos/actualizar.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="row">
    <div class="col-1 text-left">
        <a class="btn btn-lg" data-toggle="tooltip" href="{{route('ambientes.elementos.index',$elemento->id_ambiente)}}" title="Regresar">
            <i class="fas fa-arrow-alt-circle-left fa-2x" id="icono-v"></i>
        </a>
    </div>
    <div class="col-12 col-sm-10 col-lg-8 offset-1 justify-content-center">
        <div class="card card-outline card-sena elevation-2">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 mt-2 mb-4 text-center">
                        <h3 class="card-title">Actualizar Elemento</h3>
                    </div>
                </div>
                <form class="needs-validation" method="POST" action="{{route('ambientes.elementos.update',[$elemento->id_elemento_ambiente, $elemento->id_ambiente])}}" novalidate>
                    @csrf
                    @method('PATCH')
                    <div class="form-row justify-content-center">
                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="numero_inventario">Número Inventario</label>
                            <input type="text" class="form-control" id="numero_inventario" name="numero_inventario" maxlength="20" value="{{$elemento->numero_inventario}}" autofocus>
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="serial">Serial</label>
                            <input type="text" class="form-control" id="serial" name="serial" maxlength="20" value="{{$elemento->serial}}">
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-8">
                            <label class="form-label" for="id_categoria_elemento">Categoria</label>
                            <select class="custom-select" name="id_categoria_elemento" id="id_categoria_elemento">
                                <option value="{{$elemento->subcategoria_elemento->categoria_elemento->id_categoria_elemento}}" selected>{{$elemento->subcategoria_elemento->categoria_elemento->categoria_elemento}}</option>
                                @foreach ($categorias as $categoria)
                                    <option value="{{$categoria->id_categoria_elemento}}">{{$categoria->categoria_elemento}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-8">
                            <label class="form-label" for="subcategoria_elemento_id">Subcategoria</label>
                            <select class="custom-select" name="subcategoria_elemento_id" id="subcategoria_elemento_id" src="{{route('elementos_subcategorias.getsubcategorias','#')}}">
                                <option value="{{$elemento->subcategoria_elemento_id}}" selected>{{$elemento->subcategoria_elemento->subcategoria_elemento}}</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="elemento_ambiente">Nombre Elemento</label>
                            <input type="text" class="form-control" id="elemento_ambiente" name="elemento_ambiente" maxlength="40" value="{{$elemento->elemento_ambiente}}">
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-10 col-lg-4">
                            <label class="form-label" for="cantidad">Cantidad</label>
                            <input type="text" class="form-control" id="cantidad" maxlength="3" name="cantidad" value="{{$elemento->cantidad}}">
                        </div>

                        <div class="form-group col-10 col-lg-4">
                            <label class="form-label" for="estado">Estado Funcionamiento</label>
                            <select class="custom-select" id="estado" name="estado">
                                <option value="{{$elemento->estado}}" selected>{{$elemento->estado}}</option>
                                @foreach ($estados as $estado)
                                    <option value="{{$estado}}">{{$estado}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-10 col-lg-4">
                            <label class="form-label" for="fecha_adquisicion">Fecha Adquisición</label>
                            <input type="date" class="form-control" id="fecha_adquisicion" name="fecha_adquisicion" value="{{$elemento->fecha_adquisicion}}">
                        </div>
                        <div class="form-group col-10 col-lg-4">
                            <label class="form-label" for="tiempo_vida_util">Tiempo Vida Util (años)</label>
                            <input type="text" class="form-control" id="tiempo_vida_util" maxlength="3" name="tiempo_vida_util" value="{{$elemento->tiempo_vida_util}}">
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-10 col-lg-4">
                            <label class="form-label" for="origen_elemento_id">Origen</label>
                            <select class="custom-select" name="origen_elemento_id" id="origen_elemento_id">
                                <option value="{{$elemento->origen_elemento->id_origen_elemento}}" selected>{{$elemento->origen_elemento->origen_elemento}}</option>
                                @foreach ($origenes as $origen)
                                    <option value="{{$origen->id_origen_elemento}}">{{$origen->origen_elemento}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group col-10 col-lg-4">
                            <label class="form-label" for="precio">Precio</label>
                            <input type="int" class="form-control" id="precio" name="precio" value="{{$elemento->precio}}">
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-10 col-lg-8">
                            <label class="form-label" for="observacion_general">Observaciones Generales</label>
                            <textarea class="form-control" id="observacion_general" name="observacion_general" rows="2">{{$elemento->observacion_general}}</textarea>
                        </div>
                    </div>

                    <div class="form-row justify-content-center mt-3 mb-4">
                        <div class="form-group col-10 col-lg-8">
                            <button type="submit" class="btn btn-naranja w-100">Actualizar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="{{asset('js/registro.js')}}"></script>
@endsection

resources/views/admin/ambientes/elementos/gestionar.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="row align-items-center mb-3">
    <div class="col-1 d-none d-lg-flex text-left">
        <a href="{{route('ambientes.index')}}" class="btn btn-lg">
            <i class="fas fa-arrow-alt-circle-left fa-2x" data-toggle="tooltip" title="Regresar" id="icono-v"></i>
        </a>
    </div>
    <div class="col-8 offset-2 offset-lg-1">
        <h3 class="card-title">Gestionar Elementos del Ambiente</h3>
    </div>
    <div class="col-1 offset-1">
        <a href="{{ route('ambientes.elementos.create',$id_ambiente) }}" type="button" class="btn btn-lg float-right">
            <i class="fas fa-plus-circle fa-2x" id="icono-v" data-toggle="tooltip" title="Asociar Elemento"></i>
        </a>
    </div>
</div>
@if (count($elementos) > 0)
    <div class="row">
        <div class="col-12">
            <div class="card card-outline card-sena elevation-2">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class="table-header">
                                <tr>
                                    <th>N°</th>
                                    <th class="text-truncate" style="max-width: 150px;">Número Inventario</th>
                                    <th>Elemento</th>
                                    <th class="text-center">Cantidad</th>
                                    <th>Estado</th>
                                    <th class="text-truncate" style="max-width: 150px;">Fecha Adquisición</th>
                                    <th class="text-center">Acciones</th>
                                </tr>
                            </thead>
                            <tbody class="table-body">
                                @foreach ($elementos as $elemento)
                                    <tr>
                                        <th scope="row">{{$loop->iteration}}</th>
                                        <td class="text-truncate" style="max-width: 150px;">{{$elemento->numero_inventario}}</td>
                                        <td class="text-truncate" style="max-width: 300px;">{{$elemento->elemento_ambiente}}</td>
                                        <td class="text-center">{{$elemento->cantidad}}</td>
                                        <td>{{$elemento->estado}}</td>
                                        <td>{{$elemento->fecha_adquisicion}}</td>
                                        <td class="text-center">
                                            <div class="row justify-content-center">
                                                <div class="col-5 col-lg-3">
                                                    <a href="{{ route('ambientes.elementos.show', [$elemento->id_elemento_ambiente,$elemento->id_ambiente]) }}" type="button">
                                                        <i class="fas fa-eye" data-toggle="tooltip" title="Detalles Elemento"></i>
                                                    </a>
                                                </div>
                                                <div class="col-5 col-lg-3">
                                                    <form action="{{ route('ambientes.elementos.destroy', [$elemento->id_elemento_ambiente, $id_ambiente]) }}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn p-0" onclick="return confirm('¿Seguro que desea Eliminar el Elemento del Ambiente?')">
                                                            <i class="fas fa-trash-alt" id="icono-v" data-toggle="tooltip" title="Eliminar Elemento"></i>
                                                        </button>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="float-right">
                            {{ $elementos->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@else
    <h4 class="mt-5" style="text-align: center">No hay elementos asociados al ambiente</h4>
@endif
@endsection

resources/views/admin/ambientes/elementos/importar.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="row">
    <div class="col-1 text-left">
        <a class="btn btn-lg" href="{{route('ambientes.elementos.index',$id_ambiente)}}">
            <i class="fas fa-arrow-alt-circle-left fa-2x" id="icono-v" data-toggle="tooltip" title="Regresar"></i>
        </a>
    </div>
    <div class="col-12 col-sm-10 col-lg-8 offset-1 justify-content-center">
        <div class="card card-outline card-sena elevation-2">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 mt-2 mb-4 text-center">
                        <h3 class="card-title">Importar Elementos</h3>
                    </div>
                </div>
                <!-- formulario Equipos-->
                <form class="needs-validation" method="POST" action="{{route('almacenar.elementos',$id_ambiente)}}" enctype="multipart/form-data" novalidate>
                    @csrf
                    <div class="form-row justify-content-center mt-4">
                        <div class="form-group col-8">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" name="elementos" id="elementos" accept=".xls,.xlsx">
                                <label class="custom-file-label" for="elementos" data-browse="Seleccionar">Archivo Excel</label>
                            </div>
                        </div>
                    </div>

                    <div class="form-row justify-content-center mt-2 mb-4">
                        <div class="form-group col-10 col-lg-8">
                            <button type="submit" class="btn btn-naranja w-100">Importar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="{{asset('js/registro.js')}}"></script>
@endsection